// Generated by CoffeeScript 1.9.1
var FloatLiteral;

FloatLiteral = (function() {
  function FloatLiteral(value) {
    this.value = value;
  }

  FloatLiteral.prototype.toString = function() {
    return this.value;
  };

  return FloatLiteral;

})();
